#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Collect QwenPaw PR-review episodes from GitHub into a JSONL file."""

from __future__ import annotations

import argparse
import json
import os
import re
from datetime import datetime, timezone
from http.client import IncompleteRead, RemoteDisconnected
from pathlib import Path
from time import sleep
from urllib.parse import quote, urlencode
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


API = "https://api.github.com"
CHECKPOINT_VERSION = 4
AI_MARKER = "Auto-generated by QwenPaw Review Agent"
META_RE = re.compile(r"<!-- qwenpaw-review-meta:(\{.*?\}) -->", re.S)
PATH_RE = re.compile(r"(?:[\w.@+-]+/)+[\w.@+-]+\.[A-Za-z0-9]+")
FILE_SUFFIXES = {
    ".css",
    ".html",
    ".js",
    ".json",
    ".jsx",
    ".less",
    ".lock",
    ".md",
    ".py",
    ".sh",
    ".toml",
    ".ts",
    ".tsx",
    ".vue",
    ".yaml",
    ".yml",
}


class GitHub:
    def __init__(self, token: str | None) -> None:
        self.headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "qwenpaw-selflearn-collector",
        }
        if token:
            self.headers["Authorization"] = f"Bearer {token}"

    def get(self, path: str, *, accept: str | None = None):
        headers = {**self.headers}
        if accept:
            headers["Accept"] = accept
        attempt = 0
        while True:
            try:
                with urlopen(
                    Request(f"{API}{path}", headers=headers),
                ) as response:
                    body = response.read().decode()
                return body if accept else json.loads(body)
            except (
                HTTPError,
                IncompleteRead,
                RemoteDisconnected,
                URLError,
            ) as error:
                if attempt == 2 or (
                    isinstance(error, HTTPError)
                    and error.code not in (502, 503, 504)
                ):
                    raise
                sleep(2**attempt)
                attempt += 1

    def pages(self, path: str, per_page: int = 100) -> list[dict]:
        items: list[dict] = []
        page = 1
        while True:
            separator = "&" if "?" in path else "?"
            data = self.get(
                f"{path}{separator}per_page={per_page}&page={page}",
            )
            batch = (
                data.get("items", data.get("workflow_runs", []))
                if isinstance(data, dict)
                else data
            )
            items.extend(batch)
            if len(batch) < per_page:
                return items
            page += 1


def iso(timestamp: str | None) -> datetime:
    return datetime.fromisoformat(
        (timestamp or "1970-01-01T00:00:00Z").replace("Z", "+00:00"),
    )


def value(data: dict, path: str) -> str | None:
    for key in path.split("."):
        data = data.get(key, {})
    return data if isinstance(data, str) else None


def between(
    items: list[dict],
    start_at: str,
    end_at: str | None,
    field: str = "created_at",
) -> list[dict]:
    return [
        item
        for item in items
        if iso(value(item, field)) > iso(start_at)
        and (not end_at or iso(value(item, field)) < iso(end_at))
    ]


def verdict(body: str) -> str | None:
    match = re.search(r'"verdict"\s*:\s*"(APPROVE|REQUEST_CHANGES)"', body)
    if match:
        return match.group(1)
    if "Changes Requested" in body:
        return "REQUEST_CHANGES"
    if "Passed AI Review" in body:
        return "APPROVE"
    return None


def is_ai_review(comment: dict) -> bool:
    return AI_MARKER in (comment.get("body") or "")


def annotate(item: dict, attribution: str, **details) -> dict:
    actor = (
        "automated" if item.get("user", {}).get("type") == "Bot" else "human"
    )
    return {
        **item,
        "_selflearn": {
            "actor": actor,
            "attribution": attribution,
            **details,
        },
    }


def temporal_relation(
    created_at: str | None,
    start_at: str,
    end_at: str,
) -> str:
    if not created_at:
        return "unknown"
    if iso(created_at) <= iso(start_at):
        return "before_episode"
    return (
        "within_episode" if iso(created_at) < iso(end_at) else "after_episode"
    )


def feedback_items(
    items: list[dict],
    start_at: str,
    end_at: str,
    field: str = "created_at",
) -> list[dict]:
    return [
        annotate(item, "temporal_only", temporal_relation="within_episode")
        for item in between(items, start_at, end_at, field)
    ]


def inline_feedback(
    items: list[dict],
    start_at: str,
    end_at: str,
) -> list[dict]:
    by_id = {item["id"]: item for item in items}
    result = []
    for item in between(items, start_at, end_at):
        parent_id = item.get("in_reply_to_id")
        parent = by_id.get(parent_id) if parent_id else None
        attribution = "temporal_only"
        if parent_id and not parent:
            attribution = "unknown_thread"
        elif parent and iso(parent["created_at"]) <= iso(start_at):
            attribution = "pre_episode_thread"
        result.append(
            annotate(
                item,
                attribution,
                temporal_relation="within_episode",
                parent_created_at=parent.get("created_at") if parent else None,
            ),
        )
    return result


def review_meta(comment: dict) -> dict | None:
    match = META_RE.search(comment.get("body") or "")
    return json.loads(match.group(1)) if match else None


def read_jsonl(path: Path) -> list[dict]:
    return [
        json.loads(line)
        for line in path.open(encoding="utf-8")
        if line.strip()
    ]


def load_backfills(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    return {
        str(item["comment_id"]): item
        for item in read_jsonl(path)
        if item.get("method") == "unique_summary_and_paths"
    }


def write_backfills(path: Path, backfills: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        for link in backfills.values():
            file.write(json.dumps(link, ensure_ascii=False) + "\n")


def load_checkpoint(path: Path, repo: str) -> dict[int, dict]:
    if not path.exists():
        return {}
    done = {}
    for line in path.open(encoding="utf-8"):
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        if (
            row.get("repo") == repo
            and row.get("version") == CHECKPOINT_VERSION
        ):
            done[int(row["pr_number"])] = row
    return done


def append_checkpoint(
    path: Path,
    repo: str,
    number: int,
    updated_at: str,
    episodes: list[dict],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as file:
        row = {
            "version": CHECKPOINT_VERSION,
            "repo": repo,
            "pr_number": number,
            "updated_at": updated_at,
            "episodes": episodes,
        }
        file.write(json.dumps(row, ensure_ascii=False) + "\n")
        file.flush()


def overview(body: str) -> dict | None:
    match = re.search(
        r"^\|\s*Changes\s*\|\s*(.+?)\s*\|?\s*$",
        body,
        re.I | re.M,
    )
    if not match:
        return None
    text = match.group(1)
    additions = re.search(
        r"\+~?\s*([\d,]+)|~?([\d,]+)\s+additions?",
        text,
        re.I,
    )
    deletions = re.search(
        r"[-−]~?\s*([\d,]+)|~?([\d,]+)\s+deletions?",
        text,
        re.I,
    )
    if not additions:
        return None
    split = re.search(
        r"(\d+)\s*files?\s+modified\s*,\s*(\d+)\s+(?:files?\s+)?added",
        text,
        re.I,
    )
    count = re.search(r"(\d+)\s*files?", text, re.I)
    changed_files = (
        sum(map(int, split.groups()))
        if split
        else int(count.group(1))
        if count
        else 1
    )
    return {
        "additions": int(
            next(group for group in additions.groups() if group).replace(
                ",",
                "",
            ),
        ),
        "deletions": int(
            next(
                (
                    group
                    for group in (deletions.groups() if deletions else ())
                    if group
                ),
                "0",
            ).replace(",", ""),
        ),
        "changed_files": changed_files,
    }


def review_paths(body: str) -> set[str]:
    match = re.search(
        r"^#{2,3}\s*3\.\s*Core Changes\s*$([\s\S]*?)(?=^#{2,3}\s*(?:4\.|Strengths))",
        body,
        re.I | re.M,
    )
    text = match.group(1) if match else body
    paths = set(PATH_RE.findall(text))
    for token in re.findall(r"`([^`\n]+)`", text):
        token = re.sub(r":\d+(?:[-–]\d+)?$", "", token)
        if (
            re.fullmatch(r"[\w.@+-]+\.[A-Za-z0-9]+", token)
            and Path(token).suffix in FILE_SUFFIXES
        ):
            paths.add(token)
    return paths


def timeline_shas(events: list[dict], created_at: str) -> set[str]:
    shas = set()
    for event in events:
        kind = event.get("event")
        committed_at = (
            event.get("created_at")
            or value(event, "committer.date")
            or value(event, "author.date")
        )
        if (
            kind == "committed"
            and committed_at
            and iso(committed_at) <= iso(created_at)
        ):
            shas.add(event.get("sha") or event.get("commit_id"))
        if (
            kind == "head_ref_force_pushed"
            and event.get("created_at")
            and iso(event["created_at"]) <= iso(created_at)
        ):
            shas.update(
                commit.get("sha")
                for commit in (
                    event.get("before_commit"),
                    event.get("after_commit"),
                )
                if commit
            )
    return {sha for sha in shas if sha is not None}


def path_matches(mentioned: set[str], changed: set[str]) -> bool:
    def matches(path: str) -> bool:
        stem = Path(path).stem
        return path in changed or any(
            candidate.endswith("/" + path) or stem in Path(candidate).parts
            for candidate in changed
        )

    return not mentioned or all(matches(path) for path in mentioned)


def historical_link(
    github: GitHub,
    repo: str,
    pr: dict,
    commits: list[dict],
    timeline: list[dict],
    comment: dict,
    compares: dict[str, dict | None],
) -> tuple[dict | None, dict]:
    summary = overview(comment["body"])
    if not summary:
        return None, {"reason": "summary_not_parsed", "candidate_count": 0}
    mentioned = review_paths(comment["body"])
    shas = timeline_shas(timeline, comment["created_at"])
    shas.update(
        commit["sha"]
        for commit in commits
        if iso(commit["commit"]["committer"]["date"])
        <= iso(comment["created_at"])
    )
    candidates = []
    available = 0
    failures = 0
    for sha in shas:
        if sha not in compares:
            try:
                compares[sha] = github.get(
                    f"/repos/{repo}/compare/{quote(pr['base']['sha'] + '...' + sha)}",
                )
            except Exception:
                compares[sha] = None
        compare = compares[sha]
        if not compare:
            failures += 1
            continue
        available += 1
        files = compare.get("files", [])
        signature = {
            "additions": sum(file["additions"] for file in files),
            "deletions": sum(file["deletions"] for file in files),
            "changed_files": len(files),
        }
        changed = {file["filename"] for file in files}
        if signature == summary and path_matches(mentioned, changed):
            candidates.append((sha, compare["merge_base_commit"]["sha"]))
    if len(candidates) != 1:
        reason = (
            "multiple_candidates" if candidates else "no_matching_candidate"
        )
        if not shas:
            reason = "no_candidate_sha"
        elif not available:
            reason = "candidate_diff_unavailable"
        return None, {
            "reason": reason,
            "candidate_count": len(candidates),
            "candidate_heads": [head for head, _ in candidates],
            "candidate_sha_count": len(shas),
            "failed_compare_count": failures,
        }
    head_sha, base_sha = candidates[0]
    return (
        {
            "comment_id": comment["id"],
            "pr_number": pr["number"],
            "base_sha": base_sha,
            "head_sha": head_sha,
            "source": "historical_backfill",
            "confidence": "medium",
            "method": "unique_summary_and_paths",
        },
        {"reason": "unique_candidate", "candidate_count": 1},
    )


def snapshot(
    github: GitHub,
    repo: str,
    link: dict | None,
    resolution: dict,
) -> dict:
    if not link:
        return {
            "base_sha": None,
            "head_sha": None,
            "diff": None,
            "source": "unresolved",
            "quality": "missing_diff",
            "resolution": resolution,
        }
    try:
        diff = github.get(
            f"/repos/{repo}/compare/{quote(link['base_sha'] + '...' + link['head_sha'])}",
            accept="application/vnd.github.v3.diff",
        )
    except Exception:
        diff = None
    if not diff:
        resolution = {"reason": "diff_unavailable", "candidate_count": 1}
    return {
        "base_sha": link["base_sha"],
        "head_sha": link["head_sha"],
        "diff": diff,
        "source": link["source"],
        "quality": "exact" if diff else "missing_diff",
        "resolution": resolution,
    }


def changes_after_review(
    github: GitHub,
    repo: str,
    start: str | None,
    end: str | None,
    review_at: str,
    pr_commit_shas: set[str],
) -> tuple[list[dict], list[dict], dict]:
    if not start or not end:
        return (
            [],
            [],
            {"status": "unresolved", "reason": "missing_boundary_sha"},
        )
    if start == end:
        return [], [], {"status": "resolved", "compare_status": "identical"}
    try:
        compare = github.get(
            f"/repos/{repo}/compare/{quote(start + '...' + end)}",
        )
    except Exception:
        return [], [], {"status": "unresolved", "reason": "compare_failed"}
    status = compare["status"]
    if status == "ahead":
        commits, candidates = [], []
        for item in compare["commits"]:
            committed_at = value(item, "commit.committer.date")
            if item["sha"] not in pr_commit_shas:
                attribution = "merged_from_base"
            elif len(item.get("parents", [])) > 1:
                attribution = "merge_commit"
            elif committed_at and iso(committed_at) <= iso(review_at):
                attribution = "pre_review_output"
            else:
                commits.append(
                    annotate(item, "graph_descendant", actor="code_change"),
                )
                continue
            candidates.append(annotate(item, attribution, actor="code_change"))
        return (
            commits,
            candidates,
            {
                "status": "resolved",
                "compare_status": status,
                "excluded_commit_count": len(candidates),
            },
        )
    candidates = [
        annotate(item, "diverged_history", actor="code_change")
        for item in compare["commits"]
    ]
    linkage = {
        "status": "resolved" if status == "identical" else "unresolved",
        "compare_status": status,
    }
    return [], candidates, linkage


def outcome(pr: dict, start_at: str, end_at: str) -> dict:
    occurred_at = pr.get("merged_at") or pr.get("closed_at")
    relation = "not_terminal"
    if occurred_at:
        if iso(occurred_at) <= iso(start_at):
            relation = "before_episode"
        elif iso(occurred_at) <= iso(end_at):
            relation = "within_episode"
        else:
            relation = "after_episode"
    return {
        "state_at_collection": pr["state"],
        "merged_at_collection": pr["merged"],
        "occurred_at": occurred_at,
        "merge_commit_sha": pr["merge_commit_sha"] if pr["merged"] else None,
        "labels_at_collection": [label["name"] for label in pr["labels"]],
        "relation": relation,
    }


def data_quality(data: dict) -> dict:
    feedback = data["feedback"]
    events = [
        item
        for key in (
            "issue_comments_after_review",
            "reviews_after_review",
            "inline_comments_after_review",
            "reactions",
        )
        for item in feedback[key]
    ]
    return {
        "snapshot": data["snapshot"]["quality"],
        "window": "valid",
        "outcome_relation": data["pr_outcome"]["relation"],
        "commit_linkage": feedback["commit_linkage"]["status"],
        "feedback_events": {
            "human": sum(
                item["_selflearn"]["actor"] == "human" for item in events
            ),
            "automated": sum(
                item["_selflearn"]["actor"] == "automated" for item in events
            ),
            "pre_episode_thread": sum(
                item["_selflearn"]["attribution"] == "pre_episode_thread"
                for item in events
            ),
            "unknown_thread": sum(
                item["_selflearn"]["attribution"] == "unknown_thread"
                for item in events
            ),
            "temporal_only": sum(
                item["_selflearn"]["attribution"] == "temporal_only"
                for item in events
            ),
            "after_episode": sum(
                item["_selflearn"].get("temporal_relation") == "after_episode"
                for item in events
            ),
        },
        "commit_candidates": len(feedback["commit_candidates"]),
    }


def episode(
    github: GitHub,
    repo: str,
    pr: dict,
    comment: dict,
    end_at: str,
    end_reason: str,
    comments: list[dict],
    reviews: list[dict],
    inline_comments: list[dict],
    link: dict | None,
    resolution: dict,
) -> dict:
    created_at = comment["created_at"]
    reactions = github.pages(
        f"/repos/{repo}/issues/comments/{comment['id']}/reactions",
    )
    return {
        "episode_id": f"{repo}#{pr['number']}:comment-{comment['id']}",
        "repo": repo,
        "pr_number": pr["number"],
        "window": {
            "start_at": created_at,
            "end_at": end_at,
            "end_reason": end_reason,
        },
        "review": {
            "comment_id": comment["id"],
            "created_at": created_at,
            "author": comment["user"]["login"],
            "body": comment["body"],
            "verdict": verdict(comment["body"]),
            "url": comment["html_url"],
        },
        "snapshot": snapshot(github, repo, link, resolution),
        "feedback": {
            "issue_comments_after_review": [
                annotate(
                    item,
                    "temporal_only",
                    temporal_relation="within_episode",
                )
                for item in between(comments, created_at, end_at)
                if not is_ai_review(item)
            ],
            "reviews_after_review": feedback_items(
                reviews,
                created_at,
                end_at,
                "submitted_at",
            ),
            "inline_comments_after_review": inline_feedback(
                inline_comments,
                created_at,
                end_at,
            ),
            "reactions": [
                annotate(
                    item,
                    "direct_reaction",
                    temporal_relation=temporal_relation(
                        item.get("created_at"),
                        created_at,
                        end_at,
                    ),
                )
                for item in reactions
            ],
            "commits_after_review": [],
            "commit_candidates": [],
            "commit_linkage": None,
        },
        "pr_outcome": outcome(pr, created_at, end_at),
        "linkage": {
            "workflow_run_id": link.get("workflow_run_id") if link else None,
            "match_method": link.get("method", "missing_review_snapshot")
            if link
            else "missing_review_snapshot",
            "confidence": link.get("confidence", "low") if link else "low",
        },
    }


def review_link(
    github: GitHub,
    repo: str,
    pr: dict,
    commits: list[dict],
    timeline: list[dict],
    comment: dict,
    backfills: dict[str, dict],
    compares: dict[str, dict | None],
) -> tuple[dict | None, dict]:
    if meta := review_meta(comment):
        return (
            {
                **meta,
                "source": "review_metadata",
                "method": "embedded_review_metadata",
                "confidence": "high",
            },
            {"reason": "embedded_metadata", "candidate_count": 1},
        )
    if backfill := backfills.get(str(comment["id"])):
        return (
            {**backfill, "source": "historical_backfill"},
            {"reason": "cached_backfill", "candidate_count": 1},
        )
    return historical_link(
        github,
        repo,
        pr,
        commits,
        timeline,
        comment,
        compares,
    )


# Collection and per-PR checkpoint updates form one ordered workflow.
# pylint: disable-next=too-many-statements
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default="agentscope-ai/QwenPaw")
    parser.add_argument("--output", default="work/selflearn/episodes.jsonl")
    parser.add_argument("--max-prs", type=int, default=200)
    parser.add_argument(
        "--snapshot-backfills",
        default="work/selflearn/snapshot_backfills.jsonl",
    )
    parser.add_argument(
        "--checkpoint",
        default="work/selflearn/episodes.checkpoint.jsonl",
    )
    args = parser.parse_args()

    github = GitHub(os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN"))
    backfills = load_backfills(Path(args.snapshot_backfills))
    checkpoint = Path(args.checkpoint)
    completed = load_checkpoint(checkpoint, args.repo)
    collected_at = (
        datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    )
    search = urlencode(
        {"q": f'repo:{args.repo} is:pr "QwenPaw AI Review" in:comments'},
    )
    prs = github.pages(f"/search/issues?{search}")[: args.max_prs]
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_suffix(output.suffix + ".tmp")
    results = {}

    for item in prs:
        number = item["number"]
        saved = completed.get(number)
        if saved and saved["updated_at"] == item["updated_at"]:
            results[number] = saved["episodes"]
            print(f"skip PR #{number} (checkpoint)")
            continue
        pr = github.get(f"/repos/{args.repo}/pulls/{number}")
        comments = github.pages(f"/repos/{args.repo}/issues/{number}/comments")
        reviews = github.pages(f"/repos/{args.repo}/pulls/{number}/reviews")
        inline_comments = github.pages(
            f"/repos/{args.repo}/pulls/{number}/comments",
        )
        commits = github.pages(
            f"/repos/{args.repo}/pulls/{number}/commits",
            per_page=50,
        )
        timeline = github.pages(f"/repos/{args.repo}/issues/{number}/timeline")
        pr_commit_shas = {commit["sha"] for commit in commits}
        compares = {}
        ai_reviews = sorted(
            filter(is_ai_review, comments),
            key=lambda row: iso(row["created_at"]),
        )
        episodes = []
        for index, comment in enumerate(ai_reviews):
            next_review = (
                ai_reviews[index + 1] if index + 1 < len(ai_reviews) else None
            )
            boundaries = [("collection_time", collected_at)]
            if next_review:
                boundaries.append(
                    ("next_ai_review", next_review["created_at"]),
                )
            terminal_at = pr.get("merged_at") or pr.get("closed_at")
            if terminal_at and iso(terminal_at) > iso(comment["created_at"]):
                boundaries.append(("pr_terminal", terminal_at))
            end_reason, end_at = min(boundaries, key=lambda row: iso(row[1]))
            link, resolution = review_link(
                github,
                args.repo,
                pr,
                commits,
                timeline,
                comment,
                backfills,
                compares,
            )
            if (
                link
                and str(comment["id"]) not in backfills
                and not review_meta(comment)
            ):
                backfills[str(comment["id"])] = link
            episodes.append(
                episode(
                    github,
                    args.repo,
                    pr,
                    comment,
                    end_at,
                    end_reason,
                    comments,
                    reviews,
                    inline_comments,
                    link,
                    resolution,
                ),
            )
        for index, data in enumerate(episodes):
            start = data["snapshot"]["head_sha"]
            end = (
                episodes[index + 1]["snapshot"]["head_sha"]
                if index + 1 < len(episodes)
                else pr["head"]["sha"]
            )
            commits_after, candidates, linkage = changes_after_review(
                github,
                args.repo,
                start,
                end,
                data["window"]["start_at"],
                pr_commit_shas,
            )
            data["feedback"]["commits_after_review"] = commits_after
            data["feedback"]["commit_candidates"] = candidates
            data["feedback"]["commit_linkage"] = linkage
            data["data_quality"] = data_quality(data)
            print(data["episode_id"])
        results[number] = episodes
        retryable = any(
            data["snapshot"]["resolution"]["reason"]
            in {
                "candidate_diff_unavailable",
                "diff_unavailable",
            }
            or data["feedback"]["commit_linkage"].get("reason")
            == "compare_failed"
            for data in episodes
        )
        if not retryable:
            append_checkpoint(
                checkpoint,
                args.repo,
                number,
                item["updated_at"],
                episodes,
            )

    with temporary.open("w", encoding="utf-8") as file:
        for item in prs:
            for data in results[item["number"]]:
                file.write(json.dumps(data, ensure_ascii=False) + "\n")
    temporary.replace(output)
    write_backfills(Path(args.snapshot_backfills), backfills)


if __name__ == "__main__":
    main()
