#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Convert raw GitHub review episodes into compact self-learning records."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


HEADER_RE = re.compile(r"^## [^\n]*QwenPaw AI Review:[^\n]*\n+")
FOOTER_RE = re.compile(
    r"\n+---\n\*Auto-generated by QwenPaw Review Agent.*?\*\s*$",
    re.S,
)
META_RE = re.compile(r"\n?<!-- qwenpaw-review-meta:.*?-->\s*$", re.S)
UNLINKED_THREADS = {"pre_episode_thread", "unknown_thread"}


def compact(**values) -> dict:
    return {
        key: value
        for key, value in values.items()
        if value is not None and value != "" and value != [] and value != {}
    }


def actor(item: dict) -> dict:
    user = item.get("user") or {}
    role = item.get("author_association", "").lower()
    return compact(
        login=user.get("login"),
        type="bot" if user.get("type") == "Bot" else "human",
        role="other" if role == "none" else role,
    )


def agent_text(body: str) -> str:
    body = META_RE.sub("", body)
    body = FOOTER_RE.sub("", body)
    return HEADER_RE.sub("", body).strip()


def reactions(item: dict) -> dict:
    return {
        key: value
        for key, value in (item.get("reactions") or {}).items()
        if key not in {"url", "total_count"} and value
    }


def target_relation(
    target_sha: str | None,
    reviewed_sha: str | None,
    later_shas: set[str],
) -> str:
    if not target_sha or not reviewed_sha:
        return "unknown"
    if target_sha == reviewed_sha:
        return "same_snapshot"
    return "later_snapshot" if target_sha in later_shas else "other_snapshot"


def event_text(item: dict, end_at: str, flags: set[str]) -> dict:
    updated_at = item.get("updated_at")
    if updated_at and updated_at > end_at:
        flags.add("post_review_event_edited_after_window")
        return {"text_status": "edited_after_window"}
    return compact(text=item.get("body"))


def code_location(item: dict) -> dict:
    end_line = item.get("original_line") or item.get("line")
    start_line = item.get("original_start_line") or item.get("start_line")
    side = item.get("side") or ""
    return compact(
        path=item.get("path"),
        start_line=start_line
        if start_line and start_line != end_line
        else None,
        end_line=end_line,
        side={"LEFT": "old", "RIGHT": "new"}.get(side, side),
        diff_hunk=item.get("diff_hunk"),
    )


def usable_event(item: dict, flags: set[str]) -> bool:
    annotation = item.get("_selflearn") or {}
    if annotation.get("attribution") in UNLINKED_THREADS:
        flags.add("unlinked_thread_event_excluded")
        return False
    if annotation.get("temporal_relation") == "after_episode":
        flags.add("out_of_window_event_excluded")
        return False
    return True


def inline_event(
    item: dict,
    end_at: str,
    reviewed_sha: str | None,
    later_shas: set[str],
    flags: set[str],
) -> dict:
    event = compact(
        event_id=f"inline-comment-{item['id']}",
        at=item.get("created_at"),
        actor=actor(item),
        code_context=code_location(item),
        target_relation=target_relation(
            item.get("original_commit_id") or item.get("commit_id"),
            reviewed_sha,
            later_shas,
        ),
        thread_relation=(
            "reply_within_episode" if item.get("in_reply_to_id") else None
        ),
        causal_link="unproven",
    )
    event.update(event_text(item, end_at, flags))
    event["reactions"] = reactions(item)
    return event


def post_review_events(
    episode: dict,
    flags: set[str],
) -> list[dict]:
    feedback = episode["feedback"]
    end_at = episode["window"]["end_at"]
    reviewed_sha = episode["snapshot"].get("head_sha")
    later_shas = {item["sha"] for item in feedback["commits_after_review"]}
    events = []
    reviews = {}

    for item in feedback["reviews_after_review"]:
        if not usable_event(item, flags):
            continue
        event = compact(
            kind="review",
            event_id=f"review-{item['id']}",
            at=item.get("submitted_at"),
            actor=actor(item),
            decision=item.get("state"),
            target_relation=target_relation(
                item.get("commit_id"),
                reviewed_sha,
                later_shas,
            ),
            causal_link="unproven",
        )
        event.update(event_text(item, end_at, flags))
        event["inline_comments"] = []
        reviews[item["id"]] = event
        events.append(event)

    for item in feedback["inline_comments_after_review"]:
        if not usable_event(item, flags):
            continue
        event = inline_event(item, end_at, reviewed_sha, later_shas, flags)
        review = reviews.get(item.get("pull_request_review_id"))
        if review:
            review["inline_comments"].append(event)
        else:
            events.append({"kind": "inline_comment", **event})

    for item in feedback["issue_comments_after_review"]:
        if not usable_event(item, flags):
            continue
        event = compact(
            kind="comment",
            event_id=f"comment-{item['id']}",
            at=item.get("created_at"),
            actor=actor(item),
            causal_link="unproven",
        )
        event.update(event_text(item, end_at, flags))
        event["reactions"] = reactions(item)
        events.append(event)

    for review in reviews.values():
        review["inline_comments"].sort(key=lambda item: item.get("at", ""))
        if not review["inline_comments"]:
            review.pop("inline_comments")
    return sorted(events, key=lambda item: item.get("at", ""))


def agent_reactions(episode: dict, flags: set[str]) -> list[dict]:
    return [
        compact(
            reaction=item.get("content"),
            at=item.get("created_at"),
            actor=actor(item),
        )
        for item in episode["feedback"]["reactions"]
        if usable_event(item, flags)
    ]


def response_changes(episode: dict) -> dict:
    feedback = episode["feedback"]
    commits = [
        compact(
            sha=item.get("sha"),
            at=(item.get("commit") or {}).get("committer", {}).get("date"),
            author=(item.get("author") or {}).get("login")
            or (item.get("commit") or {}).get("author", {}).get("name"),
            message=(item.get("commit") or {}).get("message"),
        )
        for item in feedback["commits_after_review"]
    ]
    result = {
        "commits": commits,
        "linkage": feedback["commit_linkage"]["status"],
        "causal_link": "unproven",
    }
    if commits and result["linkage"] == "resolved":
        result["diff_range"] = {
            "base_sha": episode["snapshot"].get("head_sha"),
            "head_sha": commits[-1]["sha"],
        }
    return result


def episode_outcome(episode: dict, flags: set[str]) -> dict:
    raw = episode["pr_outcome"]
    relation = raw["relation"]
    if relation != "within_episode":
        if relation in {"before_episode", "after_episode"}:
            flags.add(f"outcome_{relation}_excluded")
        return {"status": "no_terminal_outcome"}
    status = (
        "merged"
        if raw["merged_at_collection"]
        else "closed_unmerged"
        if raw["state_at_collection"] == "closed"
        else raw["state_at_collection"]
    )
    return compact(status=status, at=raw.get("occurred_at"))


def preprocess(episode: dict) -> dict:
    snapshot = episode["snapshot"]
    flags = set()
    if snapshot["quality"] != "exact":
        flags.add("reviewed_diff_missing")
    if episode["linkage"]["confidence"] == "low":
        flags.add("review_snapshot_low_confidence")
    if episode["feedback"]["commit_linkage"]["status"] != "resolved":
        flags.add("response_changes_unresolved")

    reviewed_code = compact(
        base_sha=snapshot.get("base_sha"),
        head_sha=snapshot.get("head_sha"),
        diff=snapshot.get("diff"),
        diff_status=snapshot["quality"],
        confidence=episode["linkage"]["confidence"],
    )

    events = post_review_events(episode, flags)
    output_reactions = agent_reactions(episode, flags)
    outcome = episode_outcome(episode, flags)
    return {
        "schema_version": 1,
        "episode_id": episode["episode_id"],
        "subject": {
            "repo": episode["repo"],
            "pr_number": episode["pr_number"],
        },
        "window": {
            "reviewed_at": episode["window"]["start_at"],
            "ended_at": episode["window"]["end_at"],
            "end_reason": episode["window"]["end_reason"],
        },
        "agent_output": {
            "text": agent_text(episode["review"]["body"]),
            "verdict": episode["review"]["verdict"],
            "reactions": output_reactions,
        },
        "reviewed_code": reviewed_code,
        "post_review_events": events,
        "response_changes": response_changes(episode),
        "outcome": outcome,
        "quality_flags": sorted(flags),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="work/selflearn/episodes.jsonl")
    parser.add_argument(
        "--output",
        default="work/selflearn/episodes.selflearn.jsonl",
    )
    args = parser.parse_args()

    source = Path(args.input)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with source.open(encoding="utf-8") as source_file, output.open(
        "w",
        encoding="utf-8",
    ) as output_file:
        for line in source_file:
            if not line.strip():
                continue
            output_file.write(
                json.dumps(
                    preprocess(json.loads(line)),
                    ensure_ascii=False,
                )
                + "\n",
            )
            count += 1
    print(f"wrote {count} self-learning episodes to {output}")


if __name__ == "__main__":
    main()
